<link href="modal.css" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

<?php
//CONNECT TO DB
$con = mysql_connect("mysql.alamorecords.com","alamo","blahblah");
if (!$con){
  die('Could not connect: ' . mysql_error());
}
mysql_select_db("alamorecords", $con);

//Your API Key is 9fa7f85833b56c1426444f0cfa9d8e0a
//Your secret is 83a2a174a577eb8779756760d4ad7275

$artist = $_GET['artist'];
$album = $_GET['album'];
$lastfmquery = "http://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key=9fa7f85833b56c1426444f0cfa9d8e0a&artist=" . $artist . "&album=" . $album;
$xml = simplexml_load_file($lastfmquery);
$albumsummary = $xml->album->wiki->summary;
$img = $xml->album->image;
$tracklist = $xml->album->tracks->track;

echo "<div class='modalright'>";
echo "<p><span class='albumsummary'><strong>Album Description</strong> (generated by last.fm)<br>";

if($albumsummary==""){
echo "An album description is not available from last.fm.</span>";	
}
else{
echo $albumsummary . "</span>";
}

echo "<span class='tracklist'><p><strong>Track Listing</strong> (generated by last.fm)";

if ($tracklist==""){
  echo "<br>Tracklist unavailable";	
}
else{
  foreach ($tracklist as $trackname) {
	echo "<br>" . $trackname->name;
  }
}
echo "</span></div>";

echo "<div class='modalleft'>";
echo "<h2>" . $artist . " - " . $album . "</h2>";

echo "<table style='border:0;'><tr><td><p>Condition: Very Good<br>Catalog#: 654EDAS-G6s</td>";
echo "<td><form method='post' action='' class='jcart' id='addtocart'>
  <fieldset>
    <input type='hidden' name='my-item-id' value='Bob Dylan - Lay Lady Lay' />
    <input type='hidden' name='my-item-name' value='Bob Dylan - Lay Lady Lay' />
    <input type='hidden' name='my-item-price' value='30' />
    <input type='hidden' name='my-item-qty' value='1' />
    <input type='hidden' name='my-item-url' value='' />
    <input type='submit' name='my-add-button' value='Add to cart' class='button' />
  </fieldset>
</form></td></tr></table>";

echo "<p><img class='albumpic' src='" . $img[3] . "'>";
echo "</div>";

?>
